name: Package sources with release
permissions:
   contents: write

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      package_name: slicotpp-${{ github.ref_name }}-src

    steps:
    - uses: actions/checkout@v4

    - name: Create build environment
      run: mkdir build

    - name: Package source code
      working-directory: build/
      run: tar c -f build/${{ env.package_name }} include/ src/ CMakeLists.txt

    - name: Add packaged source code to release
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: ${{ env.package_name }}
        path: build/${{ env.package_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
