name: Package sources with resease
permissions:
   contents: write

on:
  release:
    tupes: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create build environment
      run: cmake -E make_directory build

    - name: Package source code
      working-directory: build/
      run: cmake --build . --target slicotpp_package

    - name: Add packaged source code to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/slicotpp-src.zip
        tag: ${{ github.ref }}
